### ISSUE TITLE
icons是这么来的

### ISSUE THREAD

**Issue by xishanxu** [xghell/xg-shop#1]
比如说home-tab-bar.js  里面iconList中的text怎么来的，怎么改变呢？

**Comment by xghell** [comment]
字体图标，我用的是阿里图标库，在App.js中引入

**Comment by Eden-Harris** [comment]
> 字体图标，我用的是阿里图标库，在App.js中引入

请问可以提供字体拷贝连接吗？比如 [阿里巴巴国际站官方图标库](https://www.iconfont.cn/collections/detail?spm=a313x.7781069.1998910419.d9df05512&cid=19238), 否则自定义图片和修改图标变得很麻烦，希望能基于你的图标库修改。

**Comment by xghell** [comment]
你需要的话我可以把用到的图标打个包，给你发个离线包。

**Comment by Eden-Harris** [comment]
@xghell   1692853539@qq.com 感谢了

**Comment by Eden-Harris** [comment]
> 你需要的话我可以把用到的图标打个包，给你发个离线包。

我看了离线包的，太麻烦了不如我自己上iconfont一个一个找好一点

**Comment by xghell** [comment]
你可以先整体引入离线字体图标，然后需要改的自己在创建一个图标库。

**Comment by lihe6666** [comment]
半成品

**Comment by xghell** [comment]
最近再写另一个项目，这个之后会慢慢完善
